### ISSUE TITLE
Imagenes faltantes

### ISSUE THREAD

**Issue by JulioFalcon-ChatGPT-Nodos** [donmerendolo/anki-carnet-B#6]
Hola, gran app, muchas gracias, creo a mi hija le ayudará a sacarse el carnet

Es posible conseguir las imágenes que faltan, GitHub indica que solo se subieron 1000 y que hubo 880 que no se subieron. Me imagino es la limitación de GitHub.

Muchas gracias

Julio Falcón

**Comment by donmerendolo** [comment]
Hola, creo que lo que pasa es que GitHub sólo muestra 1000 archivos en esa lista. Clonando el repositorio se descargan 1880 archivos en esa carpeta.
