### ISSUE TITLE
1.0 o 2.0

### ISSUE THREAD

**Issue by Kadizta98** [donmerendolo/anki-carnet-B#9]
Perdona que moleste, y para esto, pero creo que se sumó la 1.0 a la 2.0 habiendo un total de mas de 4.000 tarjetas, por lo tanto, estudio con el sumatorio de las dos versiones, o me centro solamente en las 2.0?

Un saludo y de nuevo disculpa las molestias!

Aprovecho para agradecer el TRABAJAZO!

**Comment by donmerendolo** [comment]
Mejor sólo la 2.0 aunque hayan menos. Buena parte de las preguntas de la 1.0 deben estar anticuadas.
